app/models.py
from . import db
from werkzeug.security import generate_password_hash,check_password_hash
import app
from flask_login import UserMixin
from . import login_manager
class News:
    '''
    News class to define News Objects
    '''
    def __init__(self,id,name,url,description,category, country):
        self.id =id
        self.name= name
        self.url = url
        self.description = description
        self.category = category
        self.country = country
class Articles:
    get_articles = []
    def __init__(self,title,author,url,description, urlToImage, publishedAt, content):
        self.title = title
        self.author = author
        self.url = url
        self.description= description
        self.urlToImage = urlToImage
        self.publishedAt = publishedAt
        self.content = content

class User(db.Model):
    __tablename__ = 'users'
    id = db.Column(db.Integer,primary_key = True)
    username = db.Column(db.String(255))
    role_id = db.Column(db.Integer,db.ForeignKey('roles.id'))
    pass_secure = db.Column(db.String(255))

    def __repr__(self):
        return f'User {self.username}'

class Role(db.Model):
    __tablename__ = 'roles'

    id = db.Column(db.Integer,primary_key = True)
    name = db.Column(db.String(255))
    users = db.relationship('User',backref = 'role',lazy="dynamic")

    def __repr__(self):
        return f'User {self.name}'        


    pass_secure  = db.Column(db.String(255))

    @property
    def password(self):
            raise AttributeError('You cannot read the password attribute')

    @password.setter
    def password(self, password):
        self.pass_secure = generate_password_hash(password)


    def verify_password(self,password):
        return check_password_hash(self.pass_secure,password) 

class User(UserMixin,db.Model):
    __tablename__ = 'users'

    id = db.Column(db.Integer,primary_key = True)
    username = db.Column(db.String(255),index = True)
    email = db.Column(db.String(255),unique = True,index = True)
    role_id = db.Column(db.Integer,db.ForeignKey('roles.id'))
    password_hash = db.Column(db.String(255)) 
    bio = db.Column(db.String(255))
    profile_pic_path = db.Column(db.String())
    password_secure = db.Column(db.String(255))

    @login_manager.user_loader
    def load_user(user_id):
        return User.query.get(int(user_id))
            

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,PasswordField,BooleanField,SubmitField
from wtforms.validators import Required,Email,EqualTo
from wtforms import ValidationError
from ..models import User


class RegistrationForm(FlaskForm):
    email = StringField('Your Email Address',validators=[Required(),Email()])
    username = StringField('Enter your username',validators = [Required()])
    password = PasswordField('Password',validators = [Required(), EqualTo('password_confirm',message = 'Passwords must match')])
    password_confirm = PasswordField('Confirm Passwords',validators = [Required()])
    submit = SubmitField('Sign Up')

    def validate_email(self,data_field):
            if User.query.filter_by(email =data_field.data).first():
                raise ValidationError('There is an account with that email')

    def validate_username(self,data_field):
        if User.query.filter_by(username = data_field.data).first():
            raise ValidationError('That username is taken')


class LoginForm(FlaskForm):
    email = StringField('Your Email Address',validators=[Required(),Email()])
    password = PasswordField('Password',validators =[Required()])
    remember = BooleanField('Remember me')
    submit = SubmitField('Sign In')



class UpdateProfile(FlaskForm):
    bio = TextAreaField('Tell us about you.',validators = [Required()])
    submit = SubmitField('Submit')    

app/__init__.py
from flask import Flask,app
from flask_bootstrap import Bootstrap
from config import config_options
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager

bootstrap = Bootstrap()
db = SQLAlchemy()
login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'

def create_app(config_name):

    app = Flask(__name__)

    # Creating the app configurations
    app.config.from_object(config_options[config_name])

    # Initializing flask extensions
    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)

    # Will add the views and forms

    #registering the blueprint
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    # setting config
    from .request import configure_request
    configure_request(app)


    return app

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main',__name__)
from . import views,error

app/main/views.py
from ..request import get_news,get_articles
from flask import render_template,request,redirect,url_for, abort
from . import main
from flask_login import login_required
from ..models import Reviews, User
from .forms import ReviewForm,UpdateProfile
from .. import db
#Views
@main.route('/')
def index():
    """
    view root page function that returns the index page and its data
    """
    current_news = get_news()
    print(current_news)
    title = "Welcome to the Best News Website for latest and current news"
    return render_template('index.html', title= title, current_news = current_news )
@main.route("/news/<news_id>")
def articles(news_id):
    """
    view news page function that returns the news detail page and its data from a source
    """
    #get news based on source id
    articles = get_articles(news_id)
    print(articles)
    title = f'{news_id}'
    return render_template("articles.html", articles = articles, title = title)


@main.route('/movie/review/new/<int:id>', methods = ['GET','POST'])
@login_required
def new_review(id):   

 @main.route('/user/<uname>')
 def profile(uname):
    user = User.query.filter_by(username = uname).first()

    if user is None:
        abort(404)

    return render_template("profile/profile.html", user = user)   


@main.route('/user/<uname>/update',methods = ['GET','POST'])
@login_required
def update_profile(uname):
    user = User.query.filter_by(username = uname).first()
    if user is None:
        abort(404)

    form = UpdateProfile()

    if form.validate_on_submit():
        user.bio = form.bio.data

        db.session.add(user)
        db.session.commit()

        return redirect(url_for('.profile',uname=user.username))

    return render_template('profile/update.html',form =form)

app/templates/articles.html
{% extends "base.html" %}
{% block content %}
{% for current_news in articles %}
<div class="container">
    <div class="row g-2">
        <p>{{ current_news.author}}</p>
        <p>{{current_news.title}}</p>
        <a target="_blank" href="{{ current_news.url}}">
            <p>{{ current_news.description}}</p>
        </a>
        <div class="jumbotron">
            <img class="img-responsive" src="{{current_news.urlToImage}}" width="400" height="350" alt="images">
        </div>
        <p>{{ current_news.publishedAt}}</p>
        <p>{{ current_news.content}}</p>
    </div>
</div>
{% endfor %}
{% endblock %}

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% if title %}
    <title> {{ title }}</title>
        {% else %}
        <!-- google fonts -->
    <meta
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
    <title>Welcome to the Best News Website for latest and current news</title>
    {% endif %}
</head>
<body>
        <!-- Content block -->
{% extends 'bootstrap/base.html'%}
        <!-- Navbar block  -->
{% block navbar %}
{% include 'navbar.html' %}
{% endblock %}

app/templates/fourOwfour.html
{% extends 'base.html'%}

{% block content %}
<br>
    <h1>Sorry! Page not found</h1>
{% endblock %}

app/templates/index.html
{% extends 'base.html'%}
{% import 'macros.html' as macro%}
 <!-- Styles block  -->
 {% block styles%}
    {{ super() }}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
    <link rel="stylesheet" href="{{url_for('static',filename='css/index.css')}}">
{% endblock %}
 <!-- Content block  -->
{% block content %}
 <div class="container">
    <h1  class="text-center" style="color: rgb(180, 184, 118);" >
        Sources
    </h1>
    {{macro.displayNews(current_news)}}
 </div>
{% endblock%}

app/templates/login.html
{% extends 'base.html'%}
{% import 'bootstrap/wtf.html' as wtf%}

{% block content %}
<div class="container"> 
    <div class="row">
      <div class= "col-md-2"> </div>
      <div class="col-md-8">
      <!--Flash message -->
      {% for message in get_flashed_messages() %}
        <div class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{ message }}
        </div>
      {% endfor %}
      <!-- Login form -->
      {{wtf.quick_form(login_form)}}
      <p> Don't have an account? <a href="{{url_for('auth.register')}}">Sign up here</a></p>
     </div>
     <div clas="col-md-2"> </div>
    </div>
</div>

{% endblock%}

app/templates/macros.html
{% macro displayNews(current_news_list) %} {% for current_news in
    current_news_list %}
    <div class="col-md-4">
      <div
        class="card"
        style="
          box-sizing: border-box;
          border: rgb(125, 156, 185) solid;
          padding: 2px;
          border-radius: 3%;
          margin: 5px;
          background-color: beige;
        "
      >
        <div class="card-body">
            <a href="/news/{{current_news.id}}" class="text-decoration-none">
                <h3 style="color: rgb(228, 8, 248); font-family: sans-serif"class="card-title text-center">{{ current_news.name}}</h3>
            </a>
          <p style="font-size: large; font-family: 'Open Sans', sans-serif" class="card-text">
            {{current_news.url}}
          </p>
          <a href="/news/{{current_news.id}}" class="btn btn-primary">Articles</a>
        </div>
      </div>
    </div>
    {% endfor %} {% endmacro %}

app/templates/navbar.html
<div class="navbar navbar-inverse" role="navigation">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">HOME</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">
                {% if current_user.is_authenticated %}
                <li style="color:white;padding:15px;">{{current_user.username}}</li>
                <li><a href="{{url_for('auth.logout')}}">Sign out</a></li>
                {% else %}
                <li><a href="{{url_for('auth.login')}}">Sign in</a></li>
                {%endif%}
            </ul>



        </div>

    </div>
</div>

app/templates/profile/profile.html
{% extends 'base.html'%}

{% block content %}
<div class="container">
<div class="row">
<!-- displaying  Username-->
  <div class="col-md-4">
    <h3> {{user.username| capitalize}} </h3>

    <!--Displaying user bio-->
    {% if user.bio %}
      <p> {{user.bio}}</p>
    {%else%}
      <p> {{user.username| capitalize}} has no bio </p>
    {% endif %}
  </div>

  <!--Display profile photo-->
  <div class="col-md-4">

    {% if user.profile_pic_path %}
    <img src="{{url_for('static',filename=user.profile_pic_path)}}" alt="" class="img-thumbnail">
    {%else%}
    <p>No profile picture</p>
    {% endif %}
  </div>
</div>
</div>
{% endblock %}

{% if user == current_user %}
    <a href="{{url_for('main.update_profile',uname=user.username)}}">Edit profile</a>
{% endif %}
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class="container">
  {{wtf.quick_form(form)}}
</div>
{% endblock %}